towny: true
factionsuuid: true

disabled-regions:
  # If set to true, block regen will only work in these regions
  whitelist: false
  list:
    - region1

disabled-worlds:
  # If set to true, block regen will only work in these worlds
  whitelist: false
  list:
    - world_nether

disable_crop_growth: true
#This will disable melon/pumpkin growth
disable_melon_growth: true
disable_turtle_egg: false
#This will disable bamboo and chorus plants
disable_block_growth: true

entries: []
#- material: IRON_ORE
#  break-material: CRACKED_STONE_BRICKS
#  #delay is in ticks (20=1s)
#  regen-delay: 600
#  tool:
#    allowed:
#    - npchelmet
#    message: "You need a helmet to break this!"
#    damage: 1
#  chance:
#    iron_ore: 0.5G
#    gold_ore: 0.25
#    diamond_ore: 0.01
#  #If true, drop the mined/broken block/plant
#  cancel-drop: true
#  command:
#  - delay: 0
#    as: CONSOLE
#    cmd: say {player}
#  age: 7
