name: ${project.name}
main: co.marcin.darkrise.riseresources.RiseResourcesPlugin
version: ${project.version}
authors: [Travja, GoFlish, Sentropic]
api-version: 1.13
softdepend:
- WorldGuard
- ProMCUtilities
- Oraxen
- ItemsAdder
- ProSkillApi
- ProRPGItems
- Jobs
- Lands
- Residence
- GriefPrevention
- ProtectionStones
- GriefDefender
- ProRPGCrafting
- mcMMO
commands:
  resources:
    description: The base command for ProBlockRegen
    usage: /<command> reload
    aliases: [blockregen, problockregen, pbr]