name: ${project.name}
main: com.promcteam.mirage.Mirage
version: ${project.version}
authors: [ Travja, GoFlish, Sentropic ]
api-version: 1.13
softdepend:
  - WorldGuard
  - Sapphire
  - Oraxen
  - ItemsAdder
  - Fabled
  - Divinity
  - Jobs
  - Lands
  - Residence
  - GriefPrevention
  - ProtectionStones
  - GriefDefender
  - ProRPGCrafting
  - mcMMO
commands:
  mirage:
    description: The base command for Mirage
    usage: /<command> reload
    aliases: [ resources, blockregen, problockregen, pbr ]