name: ProBlockRegen
main: co.marcin.darkrise.riseresources.RiseResourcesPlugin
version: ${project.version}
authors: [Travja, GoFlish]
api-version: 1.13
softdepend:
- WorldGuard
- ProMCUtilities
- Oraxen
- ItemsAdder
- ProRPGItems
commands:
  resources:
    description: The base command for ProBlockRegen
    usage: /<command> reload
    aliases: [blockregen, problockregen, pbr]