name: ProBlockRegen
main: co.marcin.darkrise.riseresources.RiseResourcesPlugin
version: 1.0-SNAPSHOT
authors: [Travja, GoFlish]
api-version: 1.13
softdepend:
- WorldGuard
- ProMCUtilities
commands:
  resources:
    description: The base command for ProBlockRegen
    usage: /<command> reload